openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
  contact:
    name: XXXXX


servers:
  - url: "http://localhost/rest/v1"

paths:
  /collage/student:
    get:
      summary: Get all the programs supported by this project.
      operationId: getAllStudent
      description: Get all the students
      tags:
        - student
      parameters:
        - name: city
          in: query
          description: retreive student based on city
          required: fasle
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '400':
          description: Bad Request
    post:
      summary: Create one student entity in DB.
      operationId: addStudent
      description: Create one student entity in DB
      tags:
        - student
      requestBody:
        description: student request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '200':
          description: OK
  '/collage/student/{id}':
    parameters:
      - schema:
          type: int
        name: id
        in: path
        required: true
    get:
      summary: Get one student details
      description: Get one student details
      operationId: getStudentDetails
      responses:
        '200':
          description: The request student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'


tags:
  - name: DSAPrograms
    description: Data structure programs

components:
  responses:
    Code204:
      description: No Content
  schemas:
    Student:
      title: Student
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        city:
          type: string
        age:
          type: integer
        std:
          type: integer
        stream:
          type: string